name: trigger jenkins job
on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: trigger single Job
      uses: appleboy/jenkins-action@master
      with:
        url: "https://jks.kelpglobal.com/"
        user: "6e72cb42-a078-40c6-9906-504e67649eb6"
        token: ${{ secrets.TOKEN }}
        job: "kelpv2-testing-node18"
    - name: Display Jenkins Job Triggered
      run: echo "Jenkins job has been triggered successfully."
